docs/AboutUs.md

Current implementation only consists of a blank template.
In this PR, I have added the relevant information about myself.

Edit AboutUs

---

docs/team/korochii.md

As required in tP Task 4 (Week 7).

Create a skeleton for my Project Portfolio Page (PPP)

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Address.java
src/main/java/seedu/address/model/person/Email.java
src/main/java/seedu/address/model/person/ModuleCode.java
src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/Phone.java
src/main/java/seedu/address/model/person/StudentId.java
src/main/java/seedu/address/model/person/TelegramHandle.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/storage/JsonAdaptedPerson.java
src/main/java/seedu/address/ui/PersonCard.java
src/main/resources/view/PersonListCard.fxml

**Person**: Change the constructor and fields of a Person, so that it is suitable for our user.
* Fields such as tags and address are unused and have been removed.
* Additional fields (studentId, moduleCode, telegramHandle) were added.
* Only studentId, name and moduleCode are compulsory fields.
* All fields are currently represented as Strings.
**AddCommand/Parser**: Modify according to the new Person constructor.
* Note: The Task field will only be integrated after the class is created (during the implementation of #4 )
**GUI**: Adjusted to display all the relevant fields of a student.
* Note that it does not look exactly like our Ui mockup, but can further refined next time.
<br />
<br />
**Note:**
1) The Junit test methods do NOT work and should be fixed in a separate PR.
- For now, …

Add a student

---

docs/UserGuide.md

Included some minor edits to the user guide as well.

 Add the help function in the user guide

---

src/main/java/seedu/address/logic/commands/ListCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/UniquePersonList.java

Implemented 'list' command, and updated Name class to convert name
string to title case.
The tutors can view the students enrolled in alphabetical order once
'list' command is invoked. Closes issue #3.
When the user adds or edits a students name, the name will be converted
to title case format, as this improves the uniformity of names casing.
Test cases are to be implemented.

Implemented 'list' command

---

src/main/java/seedu/address/commons/core/ManualMessages.java
src/main/java/seedu/address/logic/commands/ManualCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ManualCommandParser.java

Manual command allows users to quickly find out what commands are
available to them.
Manual command also allows users to easily understand how to use
all available commands.

Implement Manual command

---

src/main/java/seedu/address/ui/HelpWindow.java

Updated the URL for the user guide.

Fix display message in help window

---

src/main/java/seedu/address/commons/core/ManualMessages.java
src/main/java/seedu/address/logic/commands/ManualCommand.java
src/main/java/seedu/address/logic/commands/TaskCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/TaskCommandParser.java

Usage example: task i/studentID
Displays all the tasks that are allocated to a particular student.
The tasks are categorised according to the completion status as well.
Since the mark/unmark task function has not been implemented, we can change the completion status of a task to true/false manually by changing the .json file for now.
**Note: Testcases to be implemented**

Implement the task command

---

src/main/java/seedu/address/commons/core/ManualMessages.java
src/main/java/seedu/address/logic/commands/ManualCommand.java

Included handling of new commands `task`, `mark`, `unmark`, `archive` and `assign` in the manual command.

Update manual command

---

README.md
docs/AboutUs.md
docs/index.md

Replace AB3 info with TAPA's.
Also make minor edits to README and AboutUs.
closes #87

Update index.md to include TAPA's info

---

src/test/java/seedu/address/commons/core/ManualMessages.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/ManualCommandTest.java

Added test cases for manual command, handling all success cases and one failing test case.

Add test cases for manual command

---

src/test/java/seedu/address/logic/commands/EditCommandTest.java

In the current implementation, these 2 tests were commented out as they were not working.
However, it magically works now (after we corrected the implementation of the `edit` command.)

Fix test in EditCommandTest

---

src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java

Managed to fix all the failing testcases in `EditCommandParserTest` as well (realised it was because of some careless mistakes I made while copy-pasting haha)

Fix testcases in EditCommandParserTest

---

src/main/java/seedu/address/logic/parser/TaskCommandParser.java
src/test/java/seedu/address/logic/commands/TaskCommandTest.java
src/test/java/seedu/address/logic/parser/TaskCommandParserTest.java

*100% lines coverage in Intellij for both of these methods

Implement testcases for Task

---

src/main/java/seedu/address/logic/commands/AssignCommand.java
src/test/java/seedu/address/logic/commands/AssignCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/AssignCommandParserTest.java

Added test cases for the `assign` command for both Student Id and Module Code implementation.
Notes:

Add test cases for `assign`

---

docs/UserGuide.md
src/main/java/seedu/address/model/person/TelegramHandle.java

Updated telegram handle format. 
This commit effectively closes issue #168

Updated telegram handle format.

---

src/test/java/seedu/address/logic/commands/AssignCommandTest.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/SortCommandTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Add test cases for Sort Command.

Add test cases for Sort Command

---

src/test/java/seedu/address/logic/commands/TaskCommandTest.java
src/test/java/seedu/address/logic/parser/ProgressCommandParserTest.java

Implement testcases for ProgressCommandParser

---

src/test/java/seedu/address/logic/parser/ParserUtilTest.java

Added test cases for new fields in TAPA.
Removed fields used in AB3.

Implement test cases for ParserUtil

---

docs/team/korochii.md

Update the PPP

---

docs/team/benjykoh.md

Added existing features, enhanced features, contribution to project management, documentation and community.

Update PPP for Benjamin

---

src/test/java/seedu/address/storage/JsonUserPrefsStorageTest.java
src/test/java/seedu/address/storage/StorageManagerTest.java

Add testcases in Storage (`StorageManagerTest` and `JsonUserPrefsStorageTest`)
100% line coverage for both in Intellij

Add testcases in Storage

---

src/test/java/seedu/address/model/person/PersonTest.java

Handling of task list not done yet, along with some other methods in `Person`. Can merge first and work on it more if there is time.

Update Person test cases

---

src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java

Add testcases for Delete

---

docs/DeveloperGuide.md

Fixed a formatting error in the implementation for task in the DG.

Fix DG Formatting

---

docs/DeveloperGuide.md
docs/UserGuide.md
docs/team/benjykoh.md
docs/team/harish-coding.md
docs/team/korochii.md
docs/team/medajet.md

Updated DG to include assign command and deleteTask command use cases.
Updated PPP for harish-coding.

Updated DG and PPP

---

src/main/java/seedu/address/MainApp.java
src/main/java/seedu/address/model/ModelManager.java

Fixed the bug as mentioned in #148.

Update logging messages

---

src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/DeleteModuleCommandTest.java
src/test/java/seedu/address/logic/parser/DeleteModuleCommandParserTest.java

Implements testcases for the Delete Module feature, in particular for DeleteModuleCommand and DeleteModuleCommandParser. Closes #136.
Also updated testcases for Delete.

Implement testcases for DeleteModule

---

docs/DeveloperGuide.md

Add use cases in DG for Find and DeleteModule

---

docs/UserGuide.md

In order to make our UG clearer, I decided to create a new table which explains the format and the possible fields that each student can have in TAPA.

Add a new section to UG

---

docs/DeveloperGuide.md

Add manual tests to DG

---

docs/DeveloperGuide.md

Add manual testing instructions in DG for delete, deleteModule, find

---

docs/DeveloperGuide.md

Adjust list indentation to fix DG numbering. (Currently, the numbering resets after each image I added)

Adjust list indentation in DG

---

docs/UserGuide.md

Here are the things that I have fixed:
- Glossary header not in the correct format (should be ## instead of ###)
- Added missing bullet point in the note section of `assign`
- Fixed the table border as recommended by Intellij
- Added an extra note explaining how 2 students are equal only if their student ID are the same

Random UG bug fixes

---

docs/DeveloperGuide.md

Here are the things that I have fixed:
- Unbold-ed the subheaders for the use cases
- Attempt to fix indentation that causes some numbering to be wrong

Random DG bug fixes

---

docs/DeveloperGuide.md

Fix links in DG

---

docs/AboutUs.md
docs/team/brelkh.md

Also added a line to redirect Harish's PPP correctly.

Update Brandon PPP

---

docs/DeveloperGuide.md

Decided to change from a single class diagram to a table, according to feedbacks by peers.
Closes #280

Change parserUtil diagram

---

docs/DeveloperGuide.md

Deleting the table under this section as I realised I did not make a reference to it.

Delete extra ParserUtil Table under DeleteModule in DG

---

docs/DeveloperGuide.md

Removed two lines saying "more to be added" since we are about to finalise the DG.

Remove useless lines

---

docs/DeveloperGuide.md
docs/team/harish-coding.md

Updated deleteTask use case in DG, and updated PPP for harish-coding.

Updated deleteTask use case in DG, and updated PPP for harish-coding.

---

docs/DeveloperGuide.md

Reordered DG

---

docs/UserGuide.md

Update UG for Delete, Delete Module, Find

---

src/test/java/seedu/address/logic/commands/DeleteTaskCommandTest.java
src/test/java/seedu/address/logic/parser/DeleteTaskCommandParserTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalTaskIndexes.java

Implemented test cases for deleteTask command.

---

docs/DeveloperGuide.md

Shifted assign manual testing above mark and unmark.
Shifted archive manual testing to the bottom.
Change one test command in `add` as it doesn't match the sample data. (Sample data contains a student with id A0000000Z but not A0000000R)

Edit test section of dg

---

docs/DeveloperGuide.md
docs/UserGuide.md

Ugdg fixes

---

docs/UserGuide.md

Updated UG to better for pdf format.

Update CS2101 UG
