src/main/java/seedu/address/logic/commands/ArchiveCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/storage/JsonSerializableAddressBook.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

Implement the archive command, which allows user to "clone" the current .json database into a new .json file (located in the same /data folder).
The output is as follows:
**Note: The Junit test is not ready yet, and can only be implemented after we fix the existing test files. (#35)**
**Will create another issue for this after merging.**

Implement Archive command

---

src/main/java/seedu/address/logic/commands/AddCommand.java

The telegram handle field requires a minimum of 5 characters.
As such, this minor edit to the telegram handle in the `AddCommand` `MESSAGE_USAGE` ensures the given example works without error in TAPA.
Full example command will now be: `add i/A0123456Z n/John Doe m/CS2103T p/98765432 h/johnny e/e0123456@u.nus.edu `

Edit add command example

---

src/main/java/seedu/address/logic/commands/ListCommand.java

Bug in current implementation:
List does not work after using the find command.
How to replicate it:
Load TAPA -> Input "find abc" -> Input "list"
{An empty list will be displayed}
**Note: I'm not sure why this fixes it either but I hope I didn't break any feature that was implemented (especially list)**

Fix bug in list command

---

src/main/resources/view/ResultDisplay.fxml

Currently, you have to scroll sideways to read the full text so this is a trivial improvement to the ResultDisplay window.
closes #62

Implement text wrapping in ResultDisplay

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/MarkCommand.java
src/main/java/seedu/address/logic/commands/UnmarkCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/MarkCommandParser.java
src/main/java/seedu/address/logic/parser/UnmarkCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Task.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/main/java/seedu/address/model/person/exceptions/InvalidTaskIndexException.java
src/main/java/seedu/address/model/person/exceptions/PersonNotFoundException.java
src/main/java/seedu/address/model/person/exceptions/TaskAlreadyCompleteException.java
src/main/java/seedu/address/model/person/exceptions/TaskAlreadyNotCompleteException.java
src/main/java/seedu/address/ui/PersonCard.java

Implemented `mark` and `unmark` command.
Updated UserGuide.md to included prefixes for mark and unmark commands to the following format:
`mark i/STUDENT_ID idx/UNMARKED_TASK_INDEX` 
`unmark i/STUDENT_ID idx/UNMARKED_TASK_INDEX`
Example:
`mark i/A0123456X idx/1`
`unmark i/A0123456X idx/2`
**Notes:**
Have yet to implement testcases.

Implement Mark and Unmark command

---

src/main/java/seedu/address/commons/core/ManualMessages.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java

Update `edit` command to work as follows:
`edit INDEX [i/STUDENT_ID] [n/STUDENT_NAME] [m/MODULE_CODE] [p/PHONE_NUMBER] [h/TELEGRAM_HANDLE] [e/EMAIL_ADDRESS]`
eg. edit 1 i/A000000B e/johnny@gmail.com
**Notes:**
Closes #8 .
Have yet to implement testcases.
Have yet to allow students to take on multiple modules (modules could function like tags).

Update edit command to suit Person fields

---

src/main/resources/view/MainWindow.fxml

Currently, our app displays "Address App" as the title.
I think it would be more appropriate to change it to TAPA instead to fit our GUI design.

Modify title of window

---

src/main/java/seedu/address/logic/commands/MarkCommand.java
src/main/java/seedu/address/logic/commands/UnmarkCommand.java
src/main/java/seedu/address/model/person/UniquePersonList.java

Mark and unmark were not catching exceptions when an invalid index and when the tasks were already marked/unmarked respectively
The previous logic was to check if tasks were marked/unmarked first before checking if the index was even valid. The sequence was swapped to check if the index was valid first, then checking if the tasks were marked/unmarked.
Updated the logic and ensured CommandExceptions were thrown instead.

Fix bugs for mark and unmark command

---

src/main/resources/view/MainWindow.fxml

As mentioned in the previous meeting, I am proposing an improved version of the GUI that we currently have.
By using a left-right format, we will have more space to display the result of the input command (which saves us the trouble of having to scroll).
Here is the updated GUI that I am proposing:
In addition, the middle divider can be shifted horizontally, which allows the user to dynamically allocate more/less space to the person list/result display fields.

Change the format in the GUI

---

src/main/java/seedu/address/model/person/Person.java
src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
src/test/java/seedu/address/logic/commands/ClearCommandTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java

1. Accidentally included tasks in the typicalPersonsAddressBook.json that are not in titlecase, which caused JsonSerializableAddressBookTest to fail in our current implementation
2. The testcase in PersonTest is no longer applicable since our current Regex for `StudentId` does not allow for any trailing whitespace.
3. Both testcases in ClearCommandTest have to be modified since we are currently using a two-stage process for `clear`.
**Note: Might want to implement similar testcases for ConfirmClearCommand.
4. I realised the optional field in Persons might result in a `NullPointerException` when comparing between 2 `Persons` using `equals()`. In addition, changes were made to some methods in `PersonBuilder`, such that we instantiate the optional field with null instead of passing a `String …

Fix testcases

---

src/main/java/seedu/address/logic/parser/TaskCommandParser.java

Current implementation allows user input to be `task aaa i/xxx`.
Added extra preamble checks so that this will not be allowed.

Add extra checks in TaskCommandParser

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/DeleteCommandParserTest.java

Implements support for multi delete by indices. Close #95.
A change was made to an attribute in DeleteCommand to support the implementation. In particular, the `Index` attribute `targetIndex` is now an `Index` array, `targetIndices` instead.
Also updated UG to reflect the change.
TODO: DG, testcases

Implement multi delete by indices

---

src/test/java/seedu/address/logic/parser/AddressBookParserTest.java

In the current implementation, these 2 tests were commented out as they were not working.
However, it is fixed now (after we corrected the implementation of the edit command, as well as modifying the keywords in the testcase for `parseCommand_find()`)

Fix failing testcases in AddressBookParserTest

---

docs/UserGuide.md
src/main/java/seedu/address/commons/core/ManualMessages.java
src/main/java/seedu/address/logic/commands/AssignCommand.java

List of Issues to implement bug fixes:
Fix - Added warning for `add` command to warn users that student ID has to be a unique field in TAPA.
Fix - Include the prefixes for the tasks in `ManualMessages` for the `mark` and `unmark` commands.
Fix - Changed error message to imply task already assigned to one or multiple students.
Fix - Updated UserGuide to inform users that task name will be converted to Title Case.
Fix - Updated the UserGuide to specify the index of the task list, and removed the implication of the use of a separate list for done and undone tasks.

Bug fixes in v1.4 from PED

---

docs/UserGuide.md

DeleteTask description in UG included repetitive pattern.
This commit effectively closes issue #174

Updated UG deleteTask.

---

docs/UserGuide.md
src/main/java/seedu/address/model/person/TelegramHandle.java

Reverted changes made to telegram format in previous commits (Merge request #198).
Updated UG to include that telegram handle cannot have an underscore.

Fixed telegram handle format.

---

docs/UserGuide.md

Updated the UG to reflect that the user should expect an error message for the different cases of invalid indexes (such as index = 0 or negative index)
Closes #175 #178 #182

Fix PED bug for index

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/DeleteModuleCommand.java

Fixes several bugs found in the PE-D. Closes #163, closes #169, closes #187.
Also added a line to the UG for the `delete` command to clarify that all indices must be valid for the command to execute successfully (in the case of multiple indices).

Fix bugs found in PE-D

---

docs/DeveloperGuide.md

Current implementation looks like this:

Fix formatting for glossary

---

docs/DeveloperGuide.md

Updates the glossary to also include student ID/matriculation number as the terms are frequently used interchangeably.
Also changed instances of "Student ID" to "student ID" instead.

Update glossary for DG
